### ISSUE TITLE
Probléme avec la connection multi-serveurs cassandra

### ISSUE THREAD

**Issue by dooremont** [Orodan/Loodle#1]
Bonjour,
j'ai essayé de configurer avec cassandra en mode cluster...

Error initializing the database :  { [Error: All host(s) tried for query failed. First host tried, cable.oae.dc.univ-lorraine.fr:9160: Error: Socket was closed. See innerErrors.]
  innerErrors: 
   { 'db1:9160': 
      { [Error: Socket was closed]
        message: 'Socket was closed',
        info: 'Cassandra Driver Error',
        isServerUnhealthy: true },
     'db2:9160': 
      { [Error: Socket was closed]
        message: 'Socket was closed',
        info: 'Cassandra Driver Error',
        isServerUnhealthy: true },
     'db3:9160': 
      { [Error: Socket was closed]
        message: 'Socket was closed',
        info: 'Cassandra Driver Error',
        isServerUnhealthy: true } },
  info: 'Represents an error when a query cannot be performed because no host is available or could be reached by the driver.',
  message: 'All host(s) tried for query failed. First host tried, cable.oae.dc.univ-lorraine.fr:9160: Error: Socket was closed. See innerErrors.' }

j'ai modifier le fichier database.js
var system_client = new cassandra.Client({
	keyspace: 'system',
	contactPoints: ['db1:9160','db2:9160','db3:9160']
});

var client = new cassandra.Client ({
	keyspace: keyspace,
contactPoints: ['db1:9160','db2:9160','db3:9160']
});

**Comment by Orodan** [comment]
Bonjour Frédéric,

je suis en cours je regarde ça dès que je peux

Jimmy

2015-12-03 15:04 GMT+01:00 Dooremont Frédéric <notifications@github.com>:

**Comment by Orodan** [comment]
Bonsoir Frédéric,

A priori le problème que tu as est que le driver n'arrive pas à trouver tes
clusters Cassandra. C'est un problème auquel je n'ai jamais eu à faire face
en phase de développement car le cluster de Cassandra que j'utilisais était
sur ma machine et je n'ai jamais eu de problèmes à m'y connecter.
Pour essayer de résoudre ce problème j'essayerai dans un premier temps de
ne fournir qu'un seul cluster comme point d'entré au driver et de voir si
il y en a un qui fonctionne (cela indiquerait une mauvaise configuration
des autres clusters ou un problème de réseau). Cela peut paraître bête mais
il faudrait aussi vérifier dans les processus actifs sur les serveurs que
tu utilises si les clusters Cassandra sont bien lancés.

Désolé de ne pas pouvoir faire plus pour l'instant, je suis dans mes
dernières semaines de cours c'est un peu le rush.
Tiens moi au courant si la situation évolue, je testerai dès que j'en aurai
l'occasion.

Jimmy

2015-12-04 8:42 GMT+01:00 Jimmy Kasprzak <jimmykasprzak@gmail.com>:

**Comment by dooremont** [comment]
Bonsoir
le cluster est opérationnel puisque qu’une instance de OAE tourne sans problème
j’ai donc exclu tout problème réseaux ou de cassandra.
Il me semble que cela doit provenir de la configuration dans l’appli…
Mais je ne sais pas si cela peut aider
Fred

**Comment by dooremont** [comment]
Bonsoir
le cluster est opérationnel puisque qu’une instance de OAE tourne sans problème
j’ai donc exclu tout problème réseaux.
Il me semble que cela doit provenir de la configuration dans l’appli…
Mais je ne sais pas si cela peut aider
Fred

**Comment by Orodan** [comment]
Bonjour Frédéric,

ok je regarderai ça dès que je pourrais (au plus tard je retourne à la dsi
lundi 21).

Jimmy

**Comment by Orodan** [comment]
Bonjour Frédéric,

est ce que tu peux me dire quelle version de Cassandra est installée sur le
serveur ?
De plus est ce que tu as essayé de te connecter en ne précisant qu'un seul
cluster pour voir si cela fonctionnait ?

Jimmy

Le 14 décembre 2015 à 10:00, Jimmy Kasprzak <jimmykasprzak@gmail.com> a
écrit :

**Comment by Orodan** [comment]
Re-bonjour Frédéric,

j'ai réussi à surmonter mes problèmes de proxy vis à vis des machines
virtuelles ou j'ai installé des instances de Cassandra.
J'ai donc réussi à reproduire ta configuration ou tu précisais deux
"contact point" pour connecter l'application Loodle à Cassandra, mais je
n'ai aucun problème chez moi, la connexion s'établit correctement avec les
deux points.
A l'heure actuelle j'ai testé avec deux instances de Cassandra, chacune sur
un vm différente, mais qui ne sont pas reliées directement ensemble (ce ne
sont pas des noeuds du même cluster). Cependant au vu du problème que tu
m'as présenté cela ne doit faire aucune différences.

J'ai aussi effectué des recherches sur ce genre d'erreur de Cassandra et il
se trouve que dans ton log d'erreur je vois que tu essayes de te connecter
sur le port 9160, alors que par défaut Cassandra autorise des clients à se
connecter sur le port 9042. Je ne sais pas si ca vient de la configuration
du cluster ou pas, mais il me semble être une bonne idée de faire un essai
sur le port 9042.

J'espère que cela pourra t'aider, n'hésite pas à me tenir au courant

Jimmy

Le 22 décembre 2015 à 09:16, Jimmy Kasprzak <jimmykasprzak@gmail.com> a
écrit :

**Comment by dooremont** [comment]
YEs cela fonctionne …..
il a suffit de supprimer les ports dans la config…..
tu peux te connecter sur http://194.214.218.138:3000/
peux tu me donner le compte administrateur…

Ps : Peux-tu penser à m’envoyer le plan de ta présentation

merci d’avance
fred
